services:
    cli:
        image: webdevops/php-dev:8.2-alpine
        restart: "no"
        command: /bin/true
        working_dir: /app
        environment:
            REDIS_HOST: redis
        depends_on:
            - redis
        volumes:
            - ./:/app
        networks:
            - tests
        deploy:
            replicas: 0
            resources:
                limits:
                    memory: 4G

    redis:
        image: redis:5.0-alpine
        restart: always
        networks:
            - tests

networks:
    tests:
        name: "${COMPOSE_PROJECT_NAME:-laravel-better-cache}-network"
