name: Tests

on:
    push:
    pull_request:

jobs:
    phpunit:
        name: PHPUnit on PHP v${{ matrix.php }} & TestBench v${{ matrix.test-bench }} & Redis client ${{ matrix.redis-client }}

        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [8.1]
                test-bench: [^7.0]
                redis-client: [predis, phpredis]

        services:
            redis:
                image: redis:5.0
                ports:
                    - 6379/tcp
                options: --entrypoint redis-server

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: redis
                    tools: composer:v2
                    coverage: none

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                run: |
                    composer require "orchestra/testbench=${{ matrix.test-bench }}" --dev --no-update
                    composer install --prefer-dist --no-progress

            -   name: Execute phpunit
                run: composer test -- --colors=always
                env:
                    REDIS_CLIENT: ${{ matrix.redis-client }}
                    REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

    php-cs-fixer:
        name: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    extensions: dom, curl, libxml, mbstring, zip
                    tools: composer:v2
                    coverage: none

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Execute php-cs-fixer
                run: composer cs-fix -- --dry-run --diff --using-cache=no

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    tools: composer:v2
                    coverage: none

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Execute phpstan
                run: composer phpstan
